// FIX: Added exports for defaultLogo and defaultSignature to make this file a module.
// This resolves the import error in `services/api.ts`.
// Placeholder base64-encoded SVG images are provided for the logo and signature.
export const defaultLogo = 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiB2aWV3Qm94PSIwIDAgMTAwIDEwMCI+CiAgPHJlY3Qgd2lkdGg9IjEwMCIgaGVpZ2h0PSIxMDAiIGZpbGw9IiNmMGYwZjAiLz4KICA8dGV4dCB4PSI1MCIgeT0iNTUiIGZvbnQtZmFtaWx5PSJBcmlhbCwgc2Fucy1zZXJpZiIgZm9udC1zaXplPSIyMCIgdGV4dC1hbmNob3I9Im1pZGRsZSIgZmlsbD0iIzMzMyI+VVNDT1JFPC90ZXh0Pgo8L3N2Zz4=';
export const defaultSignature = `data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxNTAiIGhlaWdodD0iNTAiIHZpZXdCb3g9IjAgMCAxNTAgNTAiPgogIDx0ZXh0IHg9IjEwIiB5PSIzNSIgZm9udC1mYW1pbHk9IidCcnVzaCBTY3JpcHQgTVQnLCBjdXJzaXZlIiBmb250LXNpemU9IjMwIiBmaWxsPSIjMDAwIj5TaWduYXR1cmU8L3RleHQ+Cjwvc3ZnPg==`;
